name: Link stacked Pull-Requests
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
jobs:
  comment:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to comment your PR on the runner."
      - run: gh pr comment $PULL --body "Hi from GitHub CLI"

