name: Link to base pull-requests
run-name: Linking stacked pull-requests
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
jobs:
  comment:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        BASE_PR_NUMBER: ${{ github.event.pull_request.base.ref  }}
        REPO_PR_BASE_URL: 'https://github.com/SteveBurkert/github_reviewee/pull/'
        MY_PR_URL: '${{ env.REPO_PR_BASE_URL }})${{ github.event.number }}'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to comment your PR on the runner."
      - run: gh pr comment --body "Hi from GitHub CLI. Link to this PR is ${{ env.MY_PR_URL }})" 
