name: Link stacked Pull-Requests
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PULL --body "Hi from GitHub CLI"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
